apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: "default"
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        resources:
          limits:
            memory: "1Gi"
            cpu: "2"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "people"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        hostPath:
          path: /home/viking/Documents/pg_data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: "default"
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
